on load:
	set {_npc} to "Melany"
	clear {i::npc::%{_npc}%::*}
	set {i::npc::%{_npc}%::dialogue::1::1} to "Hi, I would like to purchase..."
	set {i::npc::%{_npc}%::dialogue::1::2} to "Just kidding. I'm still programming some stuffs."
	set {i::npc::%{_npc}%::dialogue::1::3} to "So for now, I'll allow non-developer players to use a couple of developer commands."

	set {i::npc::%{_npc}%::dialogue::2::1} to "Here's commands you are able to use in this version:"
	set {i::npc::%{_npc}%::dialogue::2::2} to "/debugmode, /debugstats, /reset <INDEX>"
	set {i::npc::%{_npc}%::dialogue::2::alt} to "Cool, no?"