function thrustATK(a: entity, r: number, d: number) :: boolean:
	loop {_r} * 2 times:
		set {_l} to location loop-value /2 blocks in front of {_a}'s head
		loop all entities in radius 1.5 of location 1 block below {_l}:
			if damageCheck({_a}, loop-entity) is true:
				set {_s} to true
				set {_l} to location 0.8 block in front of {_l}
				exit 3 sections
	
	draw 1 of sweep attack at {_l} with extra 0.0 to all players
	play sound "item.trident.throw" at {_a}
	if {_s} is true:
		loop all entities in radius 1.5 of location 1 block below {_l}:
			if damageCheck({_a}, loop-entity) is true:
				damage loop-entity by getDamage({_a}, loop-entity, {_d})
		loop 8 times:
			draw 1 of electric spark at {_l} with extra 0.8 to all players