command /stats [<offline player>]:
	aliases: /statistics, /stat
	description: Display the stats of other players
	trigger:
		if arg-1 is not set:
			set {_p} to player
		else:
			set {_p} to arg-1
		send "%nl%&7&o[%{_p}%'s Hero]"
		send "&f&l%{p::true::%{_p}'s uuid%::heroName}% &7(%{p::true::%{_p}'s uuid%::heroGender}%&7)"
		send "&eMoney: %{p::true::%{_p}'s uuid%::money}%"
		send "&7Level: %{p::true::%{_p}'s uuid%::level}% &8(%round({p::true::%{_p}'s uuid%::xp} / 10 * 100)%%%)%nl%"



